### ISSUE TITLE
[Bug] Capes and Trinkets don't drop.

### ISSUE THREAD

**Issue by ReynoldsCahoon** [Hour-of-Twilight/alpha-bug-reports#14]
**Describe the bug**
Capes and Trinkets don't drop in dungeons or solo content and can only be crafted.

**To Reproduce**
1. Run any Timeway/Dungeon/Raid
2. Get no capes/trinkets

**Expected behavior**
Capes and Trinkets should drop in the world like any other item.

**Screenshots**
None.

**Additional context**
None.

**Comment by stoneharry** [comment]
This is fixed on the dev realm.
