### ISSUE TITLE
[Bug] 10% bonus holy damage taken on Crusader's Creed

### ISSUE THREAD

**Issue by Neverlight-Jyria** [Hour-of-Twilight/alpha-bug-reports#2]
**Describe the bug**
Once u take the talent u start taking extra damage as holy damage (10%) with falldamage.

**To Reproduce**
1- Take the talent Crusader's Creed
2- Take falldamage.
3- u take 10% bonus holy falldamage

**Expected behavior**
No bonus damage on selfharm/falldamage sources

**Screenshots**
404 not found

**Additional context**
Hmm.

**Comment by ReynoldsCahoon** [comment]
This actually applies to all of the elemental masteries as shown here with Shadow's Embrace.
![image](https://user-images.githubusercontent.com/2556251/119048440-108db780-b974-11eb-88e6-ae821f7e2684.png)

**Comment by Terrorblade** [comment]
Was hotfixed shortly after alpha launch.
