### ISSUE TITLE
[Bug] Solo dungeon key hoarding

### ISSUE THREAD

**Issue by Neverlight-Jyria** [Hour-of-Twilight/alpha-bug-reports#6]
**Describe the bug**
U are able to hold alot of keys and have em saved up for speedruns

**To Reproduce**
Keep farming the keys

**Expected behavior**
Keys to vanish after dungeon or make is a unique item so u only able to have 1 in bag

**Screenshots**
404 not found.

**Additional context**
Hmm.

**Comment by tikki100** [comment]
Fixed by Tb
